title: Line Rider Web Documentation
description: API documentation for the web edition of Line Rider.
url: "malizma333.github.io"
baseurl: "/line-rider-web-docs"
repository: Malizma333/line-rider-web-docs

# Build Settings
open_url: true
theme: just-the-docs
plugins:
  - jekyll-feed

# Customization
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: 'f'

aux_links:
  "View on GitHub":
    - "https://github.com/Malizma333/line-rider-web-docs/"

back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true
gh_edit_link_text: "Contribute to these docs on GitHub"
gh_edit_repository: "https://github.com/Malizma333/line-rider-web-docs/"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"

color_scheme: dark

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

permalink: /:categories/:title