open_url: true

theme: just-the-docs
plugins:
  - jekyll-feed

title: Line Rider Web Documentation
description: API documentation for the web edition of Line Rider.
url: "malizma333.github.io"
baseurl: "/line-rider-web-docs"
repository: Malizma333/line-rider-web-docs

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

enable_copy_code_button: true

color_scheme: dark

nav_sort: case_sensitive

back_to_top: true
back_to_top_text: "Back to top"

permalink: pretty

exclude:
  # from https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # Custom
  - LICENSE
  - start.sh
  - docs/templates/

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
  focus_shortcut_key: 'f'

aux_links:
  "View on GitHub":
    - "https://github.com/Malizma333/line-rider-web-docs/"

gh_edit_link: false

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
